const objetoPost = [
    { imgPerfil:"./images/storie02.png",
    namePerf:"meowed",
    contentPostImg: "./images/gato-telefone-1.png",
    friendLike: "respondeai",
    peopleLiked: "outras 101.523 pessoas",
    nameComment: ["ronaldinho.gaucho",'ronaldo', 'tonystark'],
    comments: ["Enquanto tu tava lendo", "co foi vacilou meti o dribe aqui tbm hehe", "gatinho brabo"],
    },
    { imgPerfil:"./images/storie03.png",
    namePerf:"barked",
    contentPostImg: "./images/dog-photo.png",
    friendLike: "adorable_animals",
    peopleLiked: "utras 99.159 pessoas",
    nameComment: [],
    comments: [],
    },
    { imgPerfil:"./images/storie02.png",
    namePerf:"postcomvideo.",
    contentPostImg: "",
    srcPostVideo1: "/videos/video.mp4",
    srcPostVideo1Type: "video/mp4",
    srcPostVideo2: "/videos/video.ogv",
    srcPostVideo2Type: "video/ogv",
    srcPostVideo3: "",
    srcPostVideo3Type: "",
    friendLike: "respondeai",
    peopleLiked: "outras 101.523 pessoas",
    nameComment: ["ronaldinho.gaucho",'pessoa 02', 'pessoa 03'],
    comments: ["Tô feliz pq meu comentários automatizado pegou vei", "comentário 02", 'comentário'],
    }
];

export default objetoPost;